# Generated by Django 3.2.15 on 2022-11-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='My_Collection', max_length=128)),
                ('createDate', models.DateTimeField(auto_now=True)),
                ('buyValue', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('listValue', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('sellValue', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'collection',
            },
        ),
        migrations.CreateModel(
            name='PokeCard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('franchise', models.CharField(blank=True, choices=[('Pokemon', 'Pokemon'), ('YuGiOh', 'YuGiOh'), ('Magic', 'Magic')], default='Pokemon', max_length=32)),
                ('condition', models.CharField(blank=True, choices=[('None', None), ('MT', 'Mint'), ('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DM', 'Damaged')], default=None, max_length=32)),
                ('pokeName', models.CharField(blank=True, default=None, max_length=128)),
                ('firstEdition', models.BooleanField(blank=True, default=False)),
                ('shadowless', models.BooleanField(blank=True, default=False)),
                ('series', models.CharField(blank=True, choices=[('00', None), ('BS', 'BASE'), ('JG', 'JUNGLE'), ('FS', 'FOSSIL'), ('PRO', 'PROMO'), ('BS2', 'BASE2'), ('TR', 'TEAMROCKET'), ('GYM', 'GYM_CHALLENGE_OR_HEROES'), ('GO', 'POKEMON_GO'), ('NEO', 'NEO-REVELATION/GENESIS/DISCOVERY/DESTINY'), ('LEG', 'LEGENDARY_COLLECTION'), ('AQU', 'AQUAPOLIS'), ('SKY', 'SKYRIDGE')], default=None, max_length=128)),
                ('createDate', models.DateTimeField(auto_now=True)),
                ('purchaseDate', models.DateField(blank=True, default=None)),
                ('buyPrice', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('listPrice', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('sellPrice', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('front', models.ImageField(upload_to='collection/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.BigAutoField>/')),
                ('back', models.ImageField(upload_to='collection/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.BigAutoField>/')),
                ('notes', models.TextField(blank=True, default=None, max_length=2048)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.collection', verbose_name='collection')),
            ],
            options={
                'db_table': 'PokeCard',
            },
        ),
    ]
